### ISSUE TITLE
Layer slabs don't have a proper collision

### ISSUE THREAD

**Issue by Greenjoe12345** [CaliberMC/Caliber-Mod#4]
**Describe the bug**
Layered slabs have the same kind of hitbox as snow, sinking you into it.
**To Reproduce**
Place a layered slab, doesn't matter how many layers of it
stand on it
look in third person and see your feet sinking into it

**Expected behavior**
The collision of it should be on the top, not sunk into it.

**Screenshots**
![image](https://github.com/CaliberMC/Caliber-Mod/assets/33647525/f955c75a-4576-4a14-95f5-3b251704f787)

**Additional context**

**Comment by CaliberMC** [comment]
Thanks for pointing that one out.  I wouldn't have noticed.  I just implemented the fix for it and it will be in the next update.
