### ISSUE TITLE
Slab Buildmode removes items even in creative move.

### ISSUE THREAD

**Issue by Greenjoe12345** [CaliberMC/Caliber-Mod#5]
**Describe the bug**
When placing layered slabs, either vertical or horizontal, with slab buildmode, either with the command or holding the button, the first one will place the slab, then the second will remove the item from your inventory when you place it

**To Reproduce**
![2024-01-14_17 21 21](https://github.com/CaliberMC/Caliber-Mod/assets/33647525/1f69abd4-a88b-4e81-ac24-a4aa757c09ae)
Place the first one, it keeps the item in your inventory and makes the slab.

![2024-01-14_17 21 38](https://github.com/CaliberMC/Caliber-Mod/assets/33647525/04954dfc-002a-4880-8ed1-4922bb478210)
Place the second one, this one removes the item from your inventory when placed.

**Expected behavior**
The item should not be getting removed from your inventory in creative mode.

**Additional context**
Quarter and Eighth blocks don't cause the same issue (these don't let you build it up to a full size block with slab buildmode instead)

**Comment by CaliberMC** [comment]
This is now fixed and will be included in the next update. 0.1.4
