### ISSUE TITLE
Allow eighth blocks to have sizes like the quarter blocks

### ISSUE THREAD

**Issue by Greenjoe12345** [CaliberMC/Caliber-Mod#6]
**Is your feature request related to a problem? Please describe.**
It would be useful to have eighth blocks with the resizable feature slabs and quater blocks have, this would allow more complex shapes to be made wiht those
![image](https://github.com/CaliberMC/Caliber-Mod/assets/33647525/8c0862be-49b7-47fb-ba20-82eca9c9a647)

**Describe the solution you'd like**
Making them function like those, with clicking on it multiple times to make it larger. Though I can imagine the issue of a 2x2 pixel block possibly being too small.

**Comment by CaliberMC** [comment]
I was actually thinking about that the other day.  I might implement a whole new shape so there can be eights that grow from the corner.  And quarter slabs that grow from the side.

**Comment by CaliberMC** [comment]
This feature has been added in the last release 0.2.2.
